/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {


    public static void main(String[] args) {
        Aviao a  = new Aviao(20,120,12,55.50,2,"turbina");

       Aviao b = new Aviao(20,120,12,55.50,10,"turbina");
       System.out.println(b);
    }
}
